### PR TITLE
use makrdown, fix typo

### PR DESCRIPTION
**Pull request by retokromer**

### CODE REVIEW

**Comment by ianfixes** [comment]
We should just delete this file after converting its contents to GitHub issues.  I can set up some labels for that... There seem to be a lot of todos in the documentation scattered throughout the directories.

**Comment by retokromer** [comment]
Hmm… It would give an inflation of issues, in my personal opinion. Yet it’s up to you!

**Comment by ianfixes** [comment]
What do you mean by inflation?  

I'm not suggesting that all of these would become priorities by logging issues, just that for organization's sake we should put them into a more native form (for tracking, commenting, labelling, referencing in PRs, etc.).

**Comment by retokromer** [comment]
I mean an enormous number of issues (which make the list tedious to parse and to use). I personally would create formal issues only when there is the time and the energy to resolve them in a reasonable timeframe. Yet, as said, do it the way it’s most useful for you.

**Comment by ianfixes** [comment]
I understand.  I can always close the issues later, but in any case (whether we have the time and energy to resolve them as formal issues or not) they won't be useful while stored in this file.

For the stuff that _does_ have supporters with time & energy, I'd be glad to set up some milestones to track those.  I am in complete agreement that an unparseable list is an antipattern here.

**Pull request closed without merging**
