### PR TITLE
add compilation notes

### PR DESCRIPTION
**Pull request by retokromer**
This is a first draft regarding macOS. I will add Windows 10, as well as Debian 9.5 or Ubuntu 18.04.1 LTS as soon as… I have the time ;-)

### CODE REVIEW

**Comment by ianfixes** [comment]
We should look at #100 first just in case this has changed

**Comment by retokromer** [comment]
When will this be the case? (I will stop working on the code, and merge [my own patches](https://avpres.net/Spoiled_Apples/spoiledapples_man.pdf) only once this has been done.)

**Comment by retokromer** [comment]
@ianfixes FYI: today I also compiled and tested on Debian 9.5 and Ubuntu 16.04.5 LTS (also on Windows), as well as on Slackware 14.2.

**Comment by ianfixes** [comment]
I don't have an estimate, it depends on what comes from the discussion at https://github.com/kanjitalk755/macemu/issues/14

When I first brought this code over, I didn't realize that @kanjitalk755's fork had become the unofficial master -- many other branches from personal forks have been merged into that fork. So it may be that we need to rebase all our changes on top of that one.  Time will tell, and I don't think it will be too terrible for me to sort it all out.

**Comment by retokromer** [comment]
Is this attempt to revitalise and coordinate the project still moving forward?

**Comment by ianfixes** [comment]
Yes, although I admit I'm going down a bit of a rabbit hole regarding CI.  Travis CI's future looks tenuous, and I haven't had much luck getting stuff to compile on Appveyor.  That led me to consider Azure, given Microsoft's commitment to stand behind it.  But no matter what, my intended contribution to this project was going to be the test/release process and I haven't been able to get that working with any modern Windows tech.

**Comment by ianfixes** [comment]
What do you think of these merge conflicts btw?

**Comment by retokromer** [comment]
>What do you think of these merge conflicts btw?

I have no idea at all why there are conflicts when I wish to add a document without changing any of the already existing ones.

**Comment by retokromer** [comment]
I have put this information on [Gist](https://gist.github.com/retokromer/324bd83369010c51b7a6ada286cdb954).

**Comment by ianfixes** [comment]
> Many warnings are generated which I am investigating.

Did you reach any conclusions on these?

**Comment by retokromer** [comment]
I could silence the majority of them by cleaning the code.

**Comment by ianfixes** [comment]
I had hoped to delay merging this until I got the CI working (i.e. I wanted the compilation notes and the CI configuration to agree, as a way of verifying their correctness). Unfortunately (as of right now) there haven't been any replies to [my help forum question](https://discourse.libsdl.org/t/installing-sdl-on-ci-services-as-a-dependency/26144/2).  I'm stuck on Windows builds specifically.

**Comment by retokromer** [comment]
No problem, once it’s a good time, I can open a new PR.

**Pull request closed without merging**
