### PR TITLE
update to Markdown & rename INSTALL to install.md

### PR DESCRIPTION
**Pull request by retokromer**

### CODE REVIEW

**Comment by ianfixes** [comment]
We can ignore the appveyor error for now, I'll get that fixed.

For the code blocks, can you use "```shell" and "```diff" as appropriate so the syntax will highlight?

That will make things look a bit nicer:

```diff
--- macromasm.s.orig    Wed Jul  5 19:29:01 2000
+++ macromasm.s Wed Jul  5 19:12:34 2000
@@ -37,6 +37,8 @@
 
 #include "opt_adb.h"
 #include "assym.h"
+#include <machine/asm.h>
+#include <machine/trap.h>
         /* Define this symbol as global with (v) value */
@@ -437,8 +439,9 @@
        movw    sp@(FR_HW + 4), d0      | retrieve status register
        andw    #PSL_S, d0      | supervisor state?
        bne     Lalnosup        | branch if supervisor
-       jbsr    _mrg_aline_user | user a-line trap
-       bra     Lalrts
+       addql   #4, sp          | pop frame ptr
+       movql   #T_ILLINST, d0  | user-mode fault
+       jra     _ASM_LABEL(fault)
 Lalnosup:
 #define FR_PC (FR_HW+2)
        movl    sp@(FR_PC + 4), a0      | retrieve PC
```

and

```shell
cd src/Unix
./configure
make            # [or "gmake" if you have GNU make and "make" fails]
make install    # [optionally]
```

(don't forget to add those comment characters before the shell comments)

**Comment by ianfixes** [comment]
This looks great, thank you! 

If you have any experience building this on other platforms (i.e. with the contents of `INSTALLATION.md`), I'd love your help in setting up the CI config for this repo.

**Comment by retokromer** [comment]
I will possibly give a look during the weekend. (I did compile SheepShaver on Windows to run my old [HyperCard stacks](https://twitter.com/RetoKromer/status/1038709052673609728) :-)

**Comment by ianfixes** [comment]
Much appreciated.  I'm just trying to sift through all the available documentation, much of which is out of date.  So any scripts or snippets that work (or worked) for you will make a great starting point for me.

**Pull request merged**
