### PR TITLE
update to markdown and rename TECH to tech.md

### PR DESCRIPTION
**Pull request by retokromer**
- text to markdown
- rename file
- fix a few typos
- unify to British English

### CODE REVIEW

**Comment by ianfixes** [comment]
I'd love it you could put code snippets like `0x0000..0x1fff` and `EMULATED_68K = 1` in backticks, but I'll defer to you on whether that would be too tedious.

Also, could you name the file `TECH.md`?  Uppercase [appears to be the preferred convention](https://softwareengineering.stackexchange.com/a/301708/96409) to keep these files at the top of the alphabetical listing.

**Comment by retokromer** [comment]
By the way, should we use capitals for hex (e.g. `0x0000..0x1FFF`)?

**Comment by ianfixes** [comment]
I don't have opinions on any of the content at the moment.  My short term goals are to get the project into more "native" shape for 2019 -- the full expressive power of markdown, continuous integration for pull requests, some manner of testing framework, and the set of repo documents that folks expect to see in an open source project.

To your specific question, I'd expect the hex stuff in the docs to match the convention that's used in the code.  I haven't looked into the code style enough to know the answer there.

**Comment by retokromer** [comment]
>To your specific question, I'd expect the hex stuff in the docs to match the convention that's used in the code. I haven't looked into the code style enough to know the answer there.

I seems to use lowercase in the code.

**Pull request merged**
